# ~/.tmuxinator/default.yml
# you can make as many tabs as you wish...
# socket_name: foo # Remove to use default socket
# pre_window: rbenv shell 2.0.0-p247 # Runs in each tab and pane
# tmux_options: -f ~/.tmux.mac.conf # Pass arguments to tmux
# tmux_detached: false

name: Default project
root: ~/projects/<???>
startup_window: MISC
# pre: git fetch && eval $(cachalot env) && amazeeio-cachalot start
pre: git fetch && $EDITOR .
layout: even-vertical # #options are even-horizontal, even-vertical, main-horizontal, main-vertical, tiled
windows:
  - MISC:
      # pre: loadnvm
      # root: ~/projects/<???>
      panes:
        - cd js && yarn dev
        - git status
        - dssh
